# Generated by Django 5.2 on 2025-10-20 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat_room', '0002_initial'),
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('timestamp', models.DateTimeField()),
                ('is_deleted', models.BooleanField(default=False)),
                ('edited', models.BooleanField(default=False)),
                ('attachment', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message_parent', to='upload.attachment')),
                ('reply_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='message.message')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat_room.chatroom')),
            ],
        ),
    ]
