# Generated by Django 5.2 on 2025-11-19 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='edited',
            new_name='is_edited',
        ),
    ]
