# Generated by Django 5.2 on 2025-12-05 08:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_room', '0007_alter_chatroom_created_at_and_more'),
        ('message', '0005_alter_message_timestamp'),
        ('upload', '0002_remove_attachment_file_remove_attachment_filename_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['room', 'timestamp'], name='message_mes_room_id_438d7d_idx'),
        ),
    ]
