# Generated by Django 5.2 on 2025-12-18 13:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_room', '0011_remove_callhistory_chat_room_c_room_id_61c7ef_idx_and_more'),
        ('message', '0006_message_message_mes_room_id_438d7d_idx'),
        ('upload', '0003_rename_url_attachment_path_attachment_upload_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='message',
            name='message_mes_room_id_438d7d_idx',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='timestamp',
            new_name='created_at',
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['room', 'created_at'], name='message_mes_room_id_352b8b_idx'),
        ),
    ]
