# Generated by Django 5.2 on 2026-02-11 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0007_remove_message_message_mes_room_id_438d7d_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='attachment',
        ),
    ]
