# Generated by Django 5.2 on 2025-10-20 12:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat_room', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='memberdetail',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_roles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='memberdetail',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat_room.chatroom'),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='members',
            field=models.ManyToManyField(related_name='rooms', through='chat_room.MemberDetail', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='memberdetail',
            constraint=models.UniqueConstraint(fields=('member', 'room'), name='unique-chat-member'),
        ),
    ]
