# Generated by Django 5.2 on 2025-11-19 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_room', '0003_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='memberdetail',
            old_name='last_read_message_at',
            new_name='last_active_at',
        ),
    ]
