# Generated by Django 5.2 on 2025-10-17 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_room', '0003_initial'),
        ('group', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='group',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat', to='group.group'),
        ),
    ]
