# Generated by Django 5.2 on 2025-12-04 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_room', '0005_chatroom_created_at'),
        ('message', '0005_alter_message_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='last_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='message.message'),
        ),
    ]
