# Generated by Django 5.2 on 2025-12-05 08:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_room', '0006_chatroom_last_message'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='memberdetail',
            index=models.Index(fields=['member', 'room'], name='chat_room_m_member__2f1b11_idx'),
        ),
    ]
