# Generated by Django 5.2 on 2025-12-05 10:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_room', '0007_alter_chatroom_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='last_room_activity',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
