# Generated by Django 5.2 on 2025-12-18 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_room', '0009_callhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='callhistory',
            name='status',
            field=models.CharField(choices=[('C', 'calling'), ('S', 'started'), ('E', 'ended')], default='E', max_length=1),
            preserve_default=False,
        ),
    ]
