# Generated by Django 5.2 on 2025-12-18 13:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_room', '0010_callhistory_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='callhistory',
            name='chat_room_c_room_id_61c7ef_idx',
        ),
        migrations.RenameField(
            model_name='callhistory',
            old_name='timestamp',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='callhistory',
            name='duration',
        ),
        migrations.AddField(
            model_name='callhistory',
            name='call_type',
            field=models.CharField(choices=[('A', 'audio'), ('V', 'video')], default='A', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='callhistory',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='callhistory',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='callhistory',
            index=models.Index(fields=['room', 'created_at'], name='chat_room_c_room_id_8d0e67_idx'),
        ),
    ]
