# Generated by Django 5.2 on 2025-12-18 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_room', '0011_remove_callhistory_chat_room_c_room_id_61c7ef_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callhistory',
            name='status',
            field=models.CharField(choices=[('S', 'started'), ('E', 'ended')], max_length=1),
        ),
    ]
