# Generated by Django 5.2 on 2025-10-18 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberdetail',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='group.role'),
        ),
        migrations.AlterField(
            model_name='role',
            name='is_base_role',
            field=models.BooleanField(default=True),
        ),
    ]
