# Generated by Django 5.2 on 2025-11-16 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='memberdetail',
            old_name='last_read_message_at',
            new_name='last_active_at',
        ),
    ]
