# Generated by Django 5.2 on 2025-10-17 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0003_alter_group_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='avatar',
            field=models.ImageField(upload_to='uploads/group/avatar/'),
        ),
    ]
