# Generated by Django 5.2 on 2025-11-19 06:33

import group.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0003_rename_last_read_message_at_memberdetail_last_active_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='avatar',
            field=models.ImageField(null=True, upload_to=group.models.generate_group_avatar_url),
        ),
    ]
