# Generated by Django 5.2 on 2025-10-17 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0004_alter_group_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='is_base_role',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='role',
            name='is_master',
            field=models.BooleanField(default=False),
        ),
    ]
