# Generated by Django 5.2 on 2025-12-05 08:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0004_alter_group_avatar'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='memberdetail',
            index=models.Index(fields=['member', 'group'], name='group_membe_member__88d90b_idx'),
        ),
    ]
