# Generated by Django 5.2 on 2025-12-08 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0005_memberdetail_group_membe_member__88d90b_idx'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='is_base_role',
        ),
        migrations.RemoveField(
            model_name='role',
            name='is_master',
        ),
        migrations.AddField(
            model_name='group',
            name='base_role_permissions',
            field=models.ManyToManyField(to='group.permission'),
        ),
        migrations.AddField(
            model_name='permission',
            name='code',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
