# Generated by Django 5.2 on 2025-12-08 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0006_remove_role_is_base_role_remove_role_is_master_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=200)),
                ('code', models.IntegerField(unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='permission',
            name='code',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='base_role_permissions',
            field=models.ManyToManyField(related_name='base_roles', to='group.grouppermission'),
        ),
        migrations.AlterField(
            model_name='role',
            name='permissions',
            field=models.ManyToManyField(related_name='roles', to='group.grouppermission'),
        ),
    ]
