# Generated by Django 5.2 on 2025-12-08 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0007_grouppermission_alter_permission_code_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Permission',
        ),
    ]
