# Generated by Django 5.2 on 2025-12-09 16:17

import upload.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0008_delete_permission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='avatar',
            field=models.CharField(default=upload.utils.generate_group_avatar_url, max_length=300),
        ),
    ]
