# Generated by Django 5.2 on 2025-12-24 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0009_alter_group_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberdetail',
            name='b',
            field=models.PositiveSmallIntegerField(default=64, verbose_name='B_color_value'),
        ),
        migrations.AddField(
            model_name='memberdetail',
            name='g',
            field=models.PositiveSmallIntegerField(default=82, verbose_name='G_color_value'),
        ),
        migrations.AddField(
            model_name='memberdetail',
            name='r',
            field=models.PositiveSmallIntegerField(default=84, verbose_name='R_color_value'),
        ),
    ]
