# Generated by Django 5.2 on 2025-12-24 10:02

import group.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0010_memberdetail_b_memberdetail_g_memberdetail_r'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memberdetail',
            name='b',
        ),
        migrations.RemoveField(
            model_name='memberdetail',
            name='g',
        ),
        migrations.RemoveField(
            model_name='memberdetail',
            name='r',
        ),
        migrations.AddField(
            model_name='memberdetail',
            name='hex_color',
            field=models.CharField(default=group.utils.create_random_color_hex, max_length=7),
        ),
    ]
