# Generated by Django 5.2 on 2025-12-26 12:56

import group.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0011_remove_memberdetail_b_remove_memberdetail_g_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='hex_color',
            field=models.CharField(default=group.utils.create_random_color_hex, max_length=7),
        ),
    ]
