# Generated by Django 5.2 on 2025-12-01 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachment',
            name='file',
        ),
        migrations.RemoveField(
            model_name='attachment',
            name='filename',
        ),
        migrations.AddField(
            model_name='attachment',
            name='url',
            field=models.CharField(default='', max_length=240),
            preserve_default=False,
        ),
    ]
