# Generated by Django 5.2 on 2025-10-17 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachment',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='attachment',
            name='source_message',
        ),
    ]
