# Generated by Django 5.2 on 2025-12-09 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_remove_attachment_file_remove_attachment_filename_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attachment',
            old_name='url',
            new_name='path',
        ),
        migrations.AddField(
            model_name='attachment',
            name='upload_status',
            field=models.CharField(default='pending', max_length=60),
        ),
    ]
