# Generated by Django 5.2 on 2026-02-10 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0003_rename_url_attachment_path_attachment_upload_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachment',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='attachment',
            name='size',
        ),
        migrations.RemoveField(
            model_name='attachment',
            name='upload_status',
        ),
    ]
