# Generated by Django 5.2 on 2025-10-17 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0003_remove_attachment_sender_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProfilePicture',
        ),
    ]
