# Generated by Django 5.2 on 2026-02-10 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0004_remove_attachment_content_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='filename',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attachment',
            name='kind',
            field=models.CharField(choices=[('image', 'image'), ('video', 'video'), ('audio', 'audio'), ('document', 'document')], default='image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attachment',
            name='mime_type',
            field=models.CharField(default='', max_length=160),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attachment',
            name='size',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
