# Generated by Django 5.2 on 2026-02-11 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0008_remove_message_attachment'),
        ('upload', '0005_attachment_filename_attachment_kind_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='message',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='message.message'),
        ),
    ]
