# Generated by Django 5.2 on 2025-11-28 16:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='following',
            field=models.ManyToManyField(db_index=True, related_name='followers', to=settings.AUTH_USER_MODEL),
        ),
    ]
