# Generated by Django 5.2 on 2025-12-09 16:17

import upload.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_customuser_following'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.CharField(default=upload.utils.generate_profile_picture_url, max_length=300),
        ),
    ]
